github: [vikkshan, firtoz]
ko_fi: vikshan
custom: ["https://atlasvpn.sjv.io/vort3chs", "https://bigrock-in.sjv.io/vort3chs", "https://1.envato.market/vort3chs", "https://partners.hostgator.com/vort3chs", "hostinger.sjv.io/vort3chs", "https://namecheap.pxf.io/vort3chs"]
